### PR TITLE
Added clean implementation for the code-tool

### PR DESCRIPTION
**Pull request by hyyan**
Hope I will get some feedback this time

### CODE REVIEW

**Comment by miztroh** [comment]
Thanks for the PR.  As you might have noticed, I'm trying to address some of the older issues.  Please rebase this against master, making sure you match the whitespace / indentation style of existing code.  Also, please do not alter the sanitize function as part of this PR.

**Comment by hyyan** [comment]
Thanks for your feedbacks ,the altered code in the sanitize function is related to `pre,code` tags , and it cause the issue #49 in here 

Any idea about this ?

**Comment by miztroh** [comment]
Go ahead and submit a rebased / reformatted PR without the sanitize change and I'll take a look.  Thanks.

**Comment by hyyan** [comment]
OK

**Comment by miztroh** [comment]
Closing in favor of https://github.com/miztroh/wysiwyg-e/commit/3e01df27516c1fdc16d2ba91137622c1fa21b74f.

**Comment by hyyan** [comment]
Hello @miztroh 

I can see that you have implemented the code tool , good to know that .
But I guess the implementation is a little bit problematic 

1 - First the clear command does not clean the code block around text ,the text is just moved out of the node
2 - Creating a new code block does create a new `pre-code` around every line , not really the correct behavior.

I have mentioned these issues  before in [#49](https://github.com/miztroh/wysiwyg-e/issues/49) take a look at the GIFS.


My PR solved these problems before , I have not just had the time to update the code standard you asked for.

I guess the whole problem related to code blocks are coming from the `sanitize` function

**Should I send a new PR depending on your tool , or I just update my PR and send it back**

I have attached a Gif to explain my idea :

ysiwyg-e20160818110753

**Pull request closed without merging**
